// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  articles: dynamic(() => import("./Articles")),
  bento: dynamic(() => import("./Bento")),
  contact: dynamic(() => import("./Contact")),
  events: dynamic(() => import("./Events")),
  hero: dynamic(() => import("./Hero")),
  links_list: dynamic(() => import("./LinksList")),
  rich_text: dynamic(() => import("./RichText")),
  showcase: dynamic(() => import("./Showcase")),
  social_strip: dynamic(() => import("./SocialStrip")),
};
